image: philippheuer/docker-gitlab-powershell

stages:
  - build
  - deploy
build_job:
  stage: build
  script:
    - mkdir build
    - echo "hello test!" > build/test.txt
    - touch build/test.txt
    - pwd
  artifacts:
    paths:
      - build/test.txt


deploy_job:
  stage: deploy
  script:
   
    - echo 'test'
    - SSH_KEY=$(cat id_rsa)
    - echo "$SSH_KEY"
    - chmod +x ./hello-world.bat
    - chmod +x ./id_rsa
    - ./hello-world.bat
    #- 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y && apt-get install sshpass )'
    #- eval $(ssh-agent -s)
    #- ssh-add <(echo "$SSH_KEY")
    #- pwd=$(pwd)
    #- sshpass  -f scp -o stricthostkeychecking=no /builds/new370/test1/new.msi root@10.5.137.137:\
    #- ssh -i $SSH_KEY -o StrictHostKeyChecking=no Administrator@10.206.153.103 \
    #- scp /builds/new370/test1/new.msi  Administrator@10.206.153.103:\
    #- curl -o test.zip https://gitlab.com/new370/test1/-/jobs/5044803889/artifacts/browse/test.zip
    - bash -c "'wget --header="JOB-TOKEN: $CI_JOB_TOKEN" https://gitlab.com/new370/test1/-/jobs/5044803889/artifacts/browse/test.zip'"
    
      
  artifacts:
    paths:
      - test.zip
      - unzip test.zip
  
    