image: curlimages/curl:latest

workflow:
  rules:
    - if: 

stages:
  - upload
  - download

upload:
  stage: upload
  script:
    - 'echo $PACKAGE_VERSION > date.txt'
    - 'date >> date.txt'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file date.txt ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/ci-upload-package/$PACKAGE_VERSION/date.txt'


    

