image: philippheuer/docker-gitlab-powershell

stages:
  
  - deploy



deploy_job:
  stage: deploy
  script:
    - echo 'test'
    - chmod +x ./hello-world.bat
    - ./hello-world.bat
    - powershell -Command "Get-Date"