image: philippheuer/docker-gitlab-powershell

stages:
  - build
  - deploy
build_job:
  stage: build
  script:
    - mkdir build
    - echo "hello test!" > build/test.txt
    - touch build/test.txt
  artifacts:
    paths:
      - build/test.txt


deploy_job:
  stage: deploy
  script:
    
    - echo 'test'
    - SSH_KEY=$(cat id_rsa)
    - echo "$SSH_KEY"
    - chmod +x ./hello-world.bat
    - ./hello-world.bat
    - ssh -i $SSH_KEY -o StrictHostKeyChecking=no root@10.5.137.137:/ 

      
  artifacts:
    paths:
      - test.zip
      - unzip test.zip
  
    