image: philippheuer/docker-gitlab-powershell

stages:
  - build
  - deploy
build_job:
  stage: build
  script:
    - mkdir build
    - echo "hello test!" > build/test.txt
    - touch build/test.txt
  artifacts:
    paths:
      - build/test.txt


deploy_job:
  stage: deploy
  script:
    - echo 'test'
    - chmod +x ./hello-world.bat
    - ./hello-world.bat
    - powershell -Command "Get-Date"
    - New-item –itemtype directory –path /root/new
    - mv build  new
    - cd new
    - cat test.txt