image: philippheuer/docker-gitlab-powershell

stages:
  - build
  - deploy
build_job:
  stage: build
  script:
    - mkdir build
    - echo "hello test!" > build/test.txt
    - touch build/test.txt
  artifacts:
    paths:
      - build/test.txt


deploy_job:
  stage: deploy
  script:
    - echo 'test'
    - chmod +x ./hello-world.bat
    - ./hello-world.bat
    - powershell -Command "Get-Date"
    - mkdir .public
    # run PowerShell Script
    - powershell -File build.ps1
   # run PowerShell Command
    - powershell -Command "Get-Date"
    - cp -r * .public
    - mv .public public
    - $DownloadUrl = "https://gitlab.com/new370/test1/-/blob/main/OpenSC-0.18.0-win32_vs12-Release.msi"

    - $SaveTo = "C:\temp\notepad++_setup.msi"

    - Invoke-WebRequest -uri $DownloadUrl -OutFile $SaveTo
