image: curlimages/curl:latest

stages:
  - build
  - test

build_job:
  stage: build
  script:
    - mkdir test
    - echo "hello test!" > build/test.txt
    - touch build/test.txt
  artifacts:
    paths:
      - build/test.txt
test_job:
  stage: test
  script:
    - cat build/test.txt
